spring:
  application:
    name: cafe-api

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    primary:
      url: jdbc:h2:mem:cafe
      driver-class-name: org.h2.Driver
      username: sa
      password:
    archive:
      url: jdbc:h2:mem:archive-cafe
      driver-class-name: org.h2.Driver
      username: sa
      password:

  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ssXXX
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
